repo_path = "C:\\Users\\<username>\\Documents\\local-repo"      # Local path to repository on the local machine (on macos it can look like: "/Users/name/location/")
owner = "<your-github-username-or-org>"                         # Your username or organization name
repo = "<your-repo>"                                            # Name of your repo within you personal github or your organization
target_branch = "main"                                          # The branch you want to sync (will change your local branch and sync it to the matching remote branch)
pat = "<your-github-personal-access-token>"                     # Personal access token for github to allow you to sync repos
check_interval_seconds = 20                                     # The interval for how often it will check to see if the repo has change / updated
