[github]
owner = "<git-username>"                 # Your GitHub username
repo = "<git-repo-name>"                 # Your GitHub repo name that you will be comparing with
access_token = "<personal-access-token>" # Optional, omit if public repo

[local_repo]
path = "path/to/your/local/repo" # Input the path to your local repo
check_interval_seconds = 20      # Time between checks on the repo
